kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: worker
  extraMounts:
    - hostPath: /data/development/database
      containerPath: /mnt/database
- role: control-plane
  extraMounts:
    - hostPath: /data/development/database
      containerPath: /mnt/database
  extraPortMappings:
  - containerPort: 30000
    hostPort: 9002
  - containerPort: 30080
    hostPort: 9081
  - containerPort: 30443
    hostPort: 9444