kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: worker
  extraMounts:
    - hostPath: /data/experimental/database
      containerPath: /mnt/database
    - hostPath: /data/experimental/hyperledger
      containerPath: /mnt/hyperledger  
- role: control-plane
  extraMounts:
    - hostPath: /data/experimental/database
      containerPath: /mnt/database
    - hostPath: /data/experimental/hyperledger
      containerPath: /mnt/hyperledger  
  extraPortMappings:
  - containerPort: 30000
    hostPort: 9003
  - containerPort: 30080
    hostPort: 9082
  - containerPort: 30443
    hostPort: 9445