apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra
spec:
  clusterIP: None
  ports:
    - name: "cql"
      protocol: "TCP"
      port: 9042
      targetPort: 9042
      nodePort: 0
  selector:
    app: cassandra